### ISSUE TITLE
Create community in Spectrum platform

### ISSUE THREAD

**Issue by yhatt** [marp-team/.github#1]
We are planning to move the platform for asking to community from StackOverflow into [Spectrum](https://spectrum.chat/).

### Background

Questions asked in GitHub issue would prevent focusing development by Marp team.

The most of questions about how to write Marp presentation could resolve in community because Marp community was [backed by stars from 1K people](https://github.com/marp-team/marp/stargazers) ([+ 8K by including old Marp app](https://github.com/yhatt/marp/stargazers)).

We think [StackOverflow](http://stackoverflow.com/) is awesome platform for question with high googleability. Our support guideline has a recommendation for asking question in StackOverflow, but some people whose lacked reputations are still asking in GitHub (e.g. https://github.com/marp-team/marp-vscode/issues/109). It shows our guideline is not working well.

We should consider a new platform for question with less restrictions. We can take from some options, Slack, Discord, Discourse, Gitter, etc..., but I have recommended Spectrum by below reason:

- Public questions asked in Spectrum keeps googlability
- Marp has high affinity with many communities based on front-end development
- [Spectrum is a part of GitHub](https://spectrum.chat/spectrum/general/spectrum-is-joining-github~1d3eb8ee-4c99-46c0-8daf-ca35a96be6ce) so we can expect high integration with our repositories.

**Comment by yhatt** [comment]
It may be better for waiting [GitHub Discussions beta](https://news.ycombinator.com/item?id=22388639). I think Spectrum might be replaced with GitHub Discussions because it has already joined to GitHub.

**Comment by yhatt** [comment]
[GitHub Discussions was officially announced.](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/) A lot of Marp community users are trying to ask at GitHub so using GitHub Discussions is better than using the outside services.

I'll re-open another issue to work for using GitHub Discussions.

**Comment by kgsb24** [comment]
Any commununity links where I can ask help?

**Comment by yhatt** [comment]
@kgsb24 https://github.com/marp-team/marp/discussions
